### ISSUE TITLE
elm-test binaries

### ISSUE THREAD

**Issue by muelli** [lydell/elm-old-binaries#1]
Do you happen to have the `elm-test` binaries, too?

**Comment by lydell** [comment]
Hi! Sorry, unfortunately I don’t. I didn’t realize elm-test@0.18 relied on binaries on bintray until just now 😢

**Comment by lydell** [comment]
The binary comes from this repo I think: https://github.com/stoeffel/elm-interface-to-json

You might be able to build it from source.

**Comment by lydell** [comment]
@muelli You might want to follow along in this issue: https://github.com/rtfeldman/node-test-runner/issues/509
