### ISSUE TITLE
node 10 requirement is new (been using node 12 in prod for a long time)

### ISSUE THREAD

**Issue by 97jaz** [lydell/elm-old-binaries#2]
We ran into the `primordials is not defined` error that's mentioned in the [Discourse thread](https://discourse.elm-lang.org/t/psa-old-elm-binary-downloads-now-gone/7319/5). A commenter claims that `latest-0.18.0` requires node 10. This is surprising, since we've been using 0.18 with node 12 for a long time.

I notice that `latest-0.18.0` maps to `0.18.0-exp5` in npm, whereas it appears we've been using `0.18.0`. Is it possible that the `exp5` version, which is newer, requires an older version of node?

Unfortunately, I can't seem to find any information on what the `exp` versions changed, relative to the baseline `0.18.0`. The name kind of suggests "experimental" to me, though I really don't know.

**Comment by lydell** [comment]
https://github.com/elm-lang/elm-platform/commit/458b2f368ad69a766e365d77aef15fe8918c579c#diff-64a70cb96a5f6db5d53511643312f5c58926985b33ae90afb9c7556bd66dbd8a

The `-exp` releases seem to use binwrap instead of binstall to download binaries, but binwrap@0.1, not the latest binwrap@0.2. I suspect binwrap@0.1 is the culprit for the `primordials is not defined` error.

So it looks like one has to choose between:

- Newer Node.js support, but broken bintray links.
- Locked to Node.js 10, but working GitHub releases links.

**Comment by 97jaz** [comment]
Thanks for the explanation @lydell. If the npm packages exist just for the purpose of installing binaries, I think we can avoid this problem by just downloading them directly from this repo and avoiding npm altogether.

**Comment by lydell** [comment]
Yeah, that’s even what the npm 0.19 package hints at:

```
❯ npm i elm@latest-0.19.1

> elm@0.19.1-5 install /Users/lydell/stuff/elm/node_modules/elm
> node install.js

--------------------------------------------------------------------------------

Downloading Elm 0.19.1 from GitHub.

NOTE: You can avoid npm entirely by downloading directly from:
https://github.com/elm/compiler/releases/download/0.19.1/binary-for-mac-64-bit.gz
All this package does is download that file and put it somewhere.

--------------------------------------------------------------------------------
```

**Comment by 97jaz** [comment]
Thanks again, @lydell!

**Comment by lydell** [comment]
Have you seen https://github.com/rtfeldman/node-test-runner/issues/509#issuecomment-840567062, btw? Would be great if you could confirm that’s working so we can make a release

**Comment by 97jaz** [comment]
Yes, but this is all part of the same Docker image build process for us, so I need to get all of these issues resolved before I can test that.

**Comment by lydell** [comment]
Can’t you test locally without Docker?

**Comment by 97jaz** [comment]
It wouldn't be a terribly good test of the actual issue that we're facing. My local setup isn't the same -- different OS, different Node version, etc.
